"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@6@i355a_4u=@o38qovwj4e04l*+x$49)c#bh@6)b=al4m_!ae'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Installed Apps
    'rest_framework',
    'django_cron',
    'demo',
    # Project Create Apps
    'doxer', #'doxer.apps.DoxerConfig',
    'doxer_admin', #'doxer_admin.apps.DoxerAdminConfig',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
]

# SESSION_EXPIRE_SECONDS = 36

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
LOGOUT_REDIRECT_URL = "doxer_admin:loginpage"

# SMS_BACKEND = 'sms.backends.console.SmsBackend'
ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'HOST': 'localhost',
#         'NAME': 'doxer',
#         'USER' : 'root',
#         'PASSWORD' : '',
#         'PORT' : 3306,
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
#         }   
#     }
# }

DATABASES = {
    'default': {
        'NAME': 'softski1_doxer',
        'ENGINE': 'mysql.connector.django',
        'USER': 'softski1_demomaqu',
        'PASSWORD': 'jK(z~V+H)LIW',
        'OPTIONS': {
          'autocommit' :  True,
        },
        'TEST':{
            'COLLATION' : 'utf8mb4_unicode_ci', # is also using utf8mb4
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'Asia/Kolkata'
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False
# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


from django.contrib.messages import constants as messages

MESSAGE_TAG = {
    messages.SUCCESS :'success',
    messages.ERROR :'danger',
    messages.WARNING :'warning',
}


# Image Or Path Url
STATIC_URL = '/mylifto/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_files')
# if DEBUG:
#     STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static_files')]
# else:
#     STATIC_ROOT = os.path.join(BASE_DIR, 'static_files')

MEDIA_URL = '/mylifto/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "static_media")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS  = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "nikhil.maquinistas@gmail.com"
EMAIL_HOST_PASSWORD = "gapwjlomgyoqmokl"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.mail.yahoo.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'jim7garry@yahoo.com'
# EMAIL_HOST_PASSWORD = 'gontxrmgzljwqeww'
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

GOOGLE_API_KEY = "AIzaSyBKatjOQQPU_BHLrEth6mgq0_P2lXFNYIs"

FireBase_API_KEY = "AAAArz4KUBo:APA91bGVbwnMSAY90DLP5-4R1n7jBPZaVtqGj6ttqAaOvAJgLDB0cNGLesf4rT06n445NVeM08QNyHqU74nF_OjcRCv0g6PNy_F87qAVbIQPhV1WufUXcggiwvDO-qlc1_D7xkbkSRQ3"

CRON_CLASSES = [
    "project.cron.MyCronJob",
]

