# Generated by Django 3.2.11 on 2022-12-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0003_remove_ride_dropouttest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='fullbooked',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes'), ('2', 'Show only in Passenger Not For Driver')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='ride_pin',
            name='for_parcel',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='ride_pin',
            name='for_passenger',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
    ]
